### ISSUE TITLE
CT: Assertion failed: value should have typeof number, value=204

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#153] opened 2019-03-22 02:14 UTC
This CT error has been occurring intermittently, but regularly.  @jessegreenberg it looks like you've been doing some work that might be related, can you check this out?

```
rutherford-scattering : accessibility-fuzzBoard : require.js : run
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: value should have typeof number, value=204
Error: Assertion failed: value should have typeof number, value=204
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/axon/js/ValidatorDef.js?bust=1553215641275:198:43)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/axon/js/validate.js?bust=1553215641275:28:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/axon/js/Emitter.js?bust=1553215641275:263:11)
    at RutherfordAtom.removeParticle (https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/rutherford-scattering/js/rutherfordatom/model/RutherfordAtom.js?bust=1553215641275:55:37)
    at RutherfordAtom.moveParticle (https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/rutherford-scattering/js/rutherfordatom/model/RutherfordAtom.js?bust=1553215641275:204:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/rutherford-scattering/js/common/model/Atom.js?bust=1553215641275:93:14
    at Array.forEach (<anonymous>)
    at RutherfordAtom.moveParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/rutherford-scattering/js/common/model/Atom.js?bust=1553215641275:92:22)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1553210722888/rutherford-scattering/js/common/model/AtomSpace.js?bust=1553215641275:215:14
id: Bayes Chrome
Approximately 3/21/2019, 5:25:22 PM
```

**Comment by jessegreenberg** [comment] 2019-03-22 15:37
Yes, sorry, caused by validation of emitter args. Fixed above, closing.

**Closed by jessegreenberg** 2019-03-22 15:37 UTC
Labels: type:automated-testing, type:bug
