### ISSUE TITLE
CT blur() unsupported for Nodes using DAG

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#162] opened 2019-07-24 15:01 UTC
```
rutherford-scattering : accessibility-fuzzBoard : require.js : run
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: blur() unsupported for Nodes using DAG, accessible content is not unique
Error: Assertion failed: blur() unsupported for Nodes using DAG, accessible content is not unique
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/assert/js/assert.js:22:13)
    at HSlider.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/accessibility/Accessibility.js?:527:23)
    at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/display/Display.js?:1747:23)
    at Object.blur (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/input/A11yPointer.js?:65:33)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/input/Input.js?:1819:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/input/Input.js?:1775:12)
    at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/input/Input.js?:1047:12)
    at Input.focusoutAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/input/Input.js?:607:16)
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/axon/js/Action.js?:171:20)
    at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1563961973408/scenery/js/input/Input.js?:754:32)
id: Bayes Chrome
Approximately 7/24/2019, 3:52:53 AM
```

**Comment by jessegreenberg** [comment] 2019-07-25 02:28
There are two instances of the alpha particle energy slider now. I think it is more likely that that is new than something changed in scenery.

**Comment by jessegreenberg** [comment] 2019-07-25 02:52
It is caused by this which was recently added.
`this.controlAreaNode.accessibleOrder.push( controlPanel );`

The issue is that we are calling push on accessibleOrder, accessibleOrder is a setter so this change probably isn't working as expected.

**Comment by jessegreenberg** [comment] 2019-07-25 03:06
Fixed in the above commit.

**Closed by jessegreenberg** 2019-07-25 03:06 UTC
Labels: type:automated-testing
