### ISSUE TITLE
White line on plum pudding screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#152] opened 2018-09-25 16:01 UTC
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/194
Present in published version.
When first entering the plum pudding screen there is a white line below the legend toolbox.  Various actions cause it to disappear.  This includes switching to a new browser tab and entering projector mode.
**Steps to reproduce:**
1. IMPORTANT: Do not leave the tab or do things out of order.  Issue may not appear.
2. Start the sim fresh/refresh.
3. Go from the home screen to the plum pudding screen.  Do not go to the Rutherford atom screen first.
4. Examine the spot under the legend toolbox.  You can switch between Rutherford atom and plum pudding screen at this point.
5. Leaving the browser tab and coming back, or going to projector mode, gets rid of the problem.

**Screenshots:**
![line](https://user-images.githubusercontent.com/41024075/46026966-da57e700-c0a9-11e8-929b-a8b6928ae1c2.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Rutherford Scattering‬
URL: https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.2/phet/rutherford-scattering_all_phet_debug.html
Version: 1.1.0-rc.2 2018-09-24 15:59:53 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"41b1cf6b","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"f1a7eb07","branch":"HEAD"},"dot":{"sha":"e9a91d91","branch":"HEAD"},"joist":{"sha":"b5a39dff","branch":"HEAD"},"kite":{"sha":"08b2dbf9","branch":"HEAD"},"phet-core":{"sha":"3ec304bd","branch":"HEAD"},"phet-io":{"sha":"e42116c4","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"39a153bd","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"868e17c8","branch":"HEAD"},"phet-io-wrappers":{"sha":"97461ad8","branch":"HEAD"},"phetcommon":{"sha":"1dba8704","branch":"HEAD"},"query-string-machine":{"sha":"21fd2a0a","branch":"HEAD"},"rutherford-scattering":{"sha":"eda36d5a","branch":"HEAD"},"scenery":{"sha":"fc52c939","branch":"HEAD"},"scenery-phet":{"sha":"6027f56d","branch":"HEAD"},"sherpa":{"sha":"16fe1a7e","branch":"HEAD"},"shred":{"sha":"ef01bf40","branch":"HEAD"},"sun":{"sha":"1ae5c99a","branch":"HEAD"},"tambo":{"sha":"1995a421","branch":"HEAD"},"tandem":{"sha":"c9b53278","branch":"HEAD"}}

</details>

**Comment by KatieWoe** [comment] 2018-09-25 16:02
Am not seeing on firefox or edge.

**Comment by jessegreenberg** [comment] 2018-09-25 16:12
Very strange! I am not seeing this in Windows 10 Chrome Version 69.0.3497.100 (Official Build) (64-bit), which is the same platform that @KatieWoe is using.

**Comment by jessegreenberg** [comment] 2018-09-25 16:12
@KatieWoe if you have access to any other Windows 10 devices, could you please try to reproduce there? Wondering if this is machine specific.

**Comment by KatieWoe** [comment] 2018-09-25 16:49
@jessegreenberg I did just check on our other Win 10 on chrome and I didn't see it there.  Very odd.  I'll poke around a bit on my laptop and see if anything fixes it on my end.

**Comment by jessegreenberg** [comment] 2018-09-25 17:09
Thanks for looking into it @KatieWoe, please let me know either way. If it turns out to not be producible anywhere else, we may not try to debug this one.

**Comment by jessegreenberg** [comment] 2018-09-27 18:35
In the QA issue, @KatieWoe said
> @jessegreenberg Haven't found anything else. Doesn't seem to show up on our other Win 10 device, but I can't find any weird settings on mine that might be causing it. Sorry I don't have much to go on.

@ariel-phet based on this can we mark as wontfix?

**Comment by ariel-phet** [comment] 2018-09-28 22:14
Yes, I think fair to mark wontfix.

Closing

**Closed by ariel-phet** 2018-09-28 22:14 UTC
Labels: type:bug, type:wontfix
