### ISSUE TITLE
Keybaord Navigation testing results

### ISSUE THREAD

**Issue by terracoda** [phetsims/rutherford-scattering#125] opened 2017-10-19 19:02 UTC
Now Testing Keyboard Nav for Built Version

**Firefox 56 on Mac OsX Sierra 10.12.3**
- Focus order good: Alpha Particle Source button, Alpha Particle Slider, Traces checkbox, Protons Left Arrow, Protons Right Arrow, Protons Slider, Neutrons Left Arrow, Neutrons Right Arrow, Neutrons Slider, Radio Button Group, Play/Pause button, Reset, PhET Menu button.
- Scene Selection buttons operable with arrow keys
- [ ] Sim Screen buttons not focusable (known issue)
- [ ] Also noticed that using any slider actually restarts the flow of Alpha particles or Alpha particle traces, but using the Left and Right tweaker buttons do not restart the flow. They can cause the traces to zig zag. Not sure what it is supposed to do.
- [ ] Pressing and holding any of the sliders when the screen has active stuff in it causes the active stuff to disappear (including the atom) and nothing comes back until I reload the browser. 

**Safari 10.0.3**
- same as above
- Radio button group without cycle-through (known Safari issue) 

**Chrome Version 61.0.3163.100 with ChromeVox**
- same as FF, Except for on page load, the vitual cursor seems to start on the PhET Menu Button. Ideally it would start on an H1 for the sim, but I know this is not about screen reader access.

Sorry, I tested the wrong version first.

**Comment by terracoda** [comment] 2017-10-19 19:04
@mbarlow12 should I be testing the 1.0.6-rc.1?

**Comment by terracoda** [comment] 2017-10-19 19:14
In 1.0.6-rc.1 version

FF
Same issues EXCEPT 
- radiobutton group is keyboard focusble and operable with arrow keys.
- Tab order starts with Reset, then goes to radios, then to rest of controls
- Home Screen Button is focusable
- Sim Screen button are operable
- [ ] Sim Screen button focus highlight stays around on the Home Screen when I select the Home Screen button from within the either of the sim screens
- [ ] Similar issues on Plum Pudding screen: Pause/Play, Alpha Slider and Alpha Particles Source button not focusble.

**Comment by jessegreenberg** [comment] 2017-10-19 19:18
@terracoda 1.0.6 is the version that was deployed publicly to the PhET website, and 1.0.6-rc.1 was the release candidate that was QA tested.  More robust keyboard navigation has been added since then, can you please test to see if this is an issue for master? If you cannot VPN into phettest we can deploy a dev version, just let us know.

**Comment by terracoda** [comment] 2017-10-19 19:20
Thanks @jessegreenberg.  I did go through the VPN and went to the Dev link. Is that not the way to get the latest version of something? Which link am I suppose to go to on phettest?

**Comment by terracoda** [comment] 2017-10-19 19:27
OK, I think I am just supposed to click on the sim name. No wonder I haven't been able to find the latest for other sims :-P

**Comment by jessegreenberg** [comment] 2017-10-19 19:29
That is correct @terracoda, the sim name on the left is a link to latest.

**Comment by terracoda** [comment] 2017-10-19 20:13
@mbarlow12 and @jessegreenberg, I tested the Built version. Keyboard Nav seems like it is working as it should. I have questions about the Tweaker/Sliders, and I found a weird bug: Pressing and holding any of the sliders makes the interactive content disappear and not come back.

**Comment by jessegreenberg** [comment] 2017-10-19 20:19
> Pressing and holding any of the sliders makes the interactive content disappear and not come back.

Thanks, how strange! I just reproduced that myself, Ill create a new issue for that.

> I have questions about the Tweaker/Sliders,

I see notes related on the meeting doc, should considerations continue there or are there other comments for this issue?

**Comment by terracoda** [comment] 2017-10-19 20:24
We can discuss the tweaker/slider stuff at the KB nav meeting. I think it is a very general issue.

And what about the zig zagging. Is that supposed to happen when using the tweakers? I would think yes.

**Comment by jessegreenberg** [comment] 2017-10-19 20:29
> And what about the zig zagging.

No, thanks, that is also an issue. Any time the tweakers are pressed all particles should reset and disappear, i will update the new issue.

Thanks @terracoda continuing with the  specifics in #126,  closing this issue.

**Closed by jessegreenberg** 2017-10-19 20:29 UTC
