### ISSUE TITLE
Alpha Particle box disappears or turns white in screenshots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rutherford-scattering#146] opened 2018-08-30 18:57 UTC
**Device**
Dell Laptop
**OS**
Win 8.1
**Browser**
Firefox
**Problem Description**
For phetsims/QA/issues/181
When taking a screenshot the Alpha Particle box will disappear or turn bright white in the screenshot.  I have so far only observed this on Win 8.1 Firefox, and will document any other instances encountered in the comments.  Most screenshots I have taken on this platform showed the issue, but a few did not.
**Steps to reproduce**
1. Go to the Rutherford Atom screen, to the nuclear scale scene
2. Set the Protons at 57 and the Neutrons at 87 (others will work as well, but I still haven't found a set range)
3. Take a screenshot.  You can also turn on traces and start the alpha particles beam.  You will see a bright white box
4. On the Plum Pudding Atom screen take a screenshot.  You will see the box has mostly disappeared.

**Screenshots**
![rutherford scattering screenshot 1](https://user-images.githubusercontent.com/41024075/44872954-1edf9680-ac54-11e8-9386-c6cc35b2f398.png)

**Comment by KatieWoe** [comment] 2018-08-30 22:25
Here are screenshots of what the issue looks like in projector mode (found by going to options in the phet menu).
![rutherford scattering screenshot 3](https://user-images.githubusercontent.com/41024075/44882615-527ce980-ac71-11e8-934e-ecf33e7d3f4e.png)
![rutherford scattering screenshot 2](https://user-images.githubusercontent.com/41024075/44882616-527ce980-ac71-11e8-9be9-e5a2f1f87672.png)

**Comment by KatieWoe** [comment] 2018-08-31 18:05
May be related to phetsims/rutherford-scattering/issues/103

**Comment by jessegreenberg** [comment] 2018-09-04 18:32
In https://github.com/phetsims/rutherford-scattering/issues/103 and also https://github.com/phetsims/scenery/issues/848 we have seen transparent content for CanvasNode when fillStyle isn't defined. Could definitely be related. Ill check if we are using any specific renderers for the panels in this sim.

**Comment by jessegreenberg** [comment] 2018-09-05 21:28
> Ill check if we are using any specific renderers for the panels

Nothing out of the ordinary, just the defaults.

I am not able to reproduce this on any of the platforms I have access to. I also tested on VM with Windows 8.1 and Firefox and I cannot reproduce there either. @jonathanolson would you be able to help investigate this bug? Pinging @ariel-phet just so he is aware of the request.

**Comment by jessegreenberg** [comment] 2018-09-17 20:19
@jonathanolson took a look at this today, neither of us were able to reproduce the problem on our machines (my Windows 10 FF and Edge, @jonathanolson Mac FF). @jonathanolson said that he would have to investigate further on the particular device since that is likely the only place that it is reproducible. It could be a platform specific canvas quirk where we look into a workaround. @ariel-phet can you please comment on the priority of this issue?

**Comment by jessegreenberg** [comment] 2018-09-18 14:04
OK, thanks @ariel-phet. Closing this issue.

**Closed by jessegreenberg** 2018-09-18 14:04 UTC
Labels: type:bug, type:wontfix
