### ISSUE TITLE
Need new plum pudding image/asset

### ISSUE THREAD

**Issue by schmitzware** [phetsims/rutherford-scattering#28] opened 2016-03-02 00:26 UTC
Can I get those electrons baked into the new one also?  :)

![screen shot 2016-03-01 at 3 51 24 pm](https://cloud.githubusercontent.com/assets/694045/13446665/31ca8538-dfca-11e5-84db-c77d0375a16c.png)

**Comment by amyh-phet** [comment] 2016-03-02 01:02
@schmitzware     Absolutely.   As far as I know, there are no issues with baking the electrons into the pudding.    I'm hopefully running new artwork by design team on Thursday and then can provide you an asset for this screen.

**Comment by schmitzware** [comment] 2016-03-02 01:34
It's currently a PNG that I just load up.

**Comment by pixelzoom** [comment] 2016-03-04 22:45
Make sure that @amyh-phet provides the Illustrator file, and that it gets checked in to assets/.

**Comment by amyh-phet** [comment] 2016-03-09 16:38
@schmitzware   Finally finished baking the plum pudding and sent you the AI file by email.    Let me know if you need any adjustments to the artwork.

**Closed** 2016-03-09 21:42 UTC
Labels: design:artwork
